// Generated by CoffeeScript 1.10.0
$(function() {
  commonFn.hbsRender({
    selector: '#navBar',
    hbs: 'nav_bar'
  });
  commonFn.hbsRender({
    selector: '#carousel',
    hbs: 'carousel'
  });
  commonFn.hbsRender({
    selector: '#imgList',
    hbs: 'img_list'
  });
  commonFn.hbsRender({
    selector: '#productsList',
    hbs: 'products_list'
  });
  commonFn.hbsRender({
    selector: '#pageFooter',
    hbs: 'page_footer'
  });
  return $('.btn-test').click(function() {
    $('#modal').modal('show');
    console.log(config.domain);
    return console.log(_.chunk(['a', 'b', 'c', 'd'], 2));
  });
});

//# sourceMappingURL=index.js.map
