// Generated by CoffeeScript 1.10.0
$(function() {
  commonFn.hbsRender({
    selector: '#bar',
    hbs: 'bar',
    dataJSON: {
      title: 'abc1'
    },
    callback: function() {
      return console.log('ccc1');
    }
  });
  return $('.btn-test').click(function() {
    $('#modal').modal('show');
    console.log(config.domain);
    return console.log(_.chunk(['a', 'b', 'c', 'd'], 2));
  });
});

//# sourceMappingURL=index.js.map
